---
- hosts: all

  pre_tasks:
    - name: load configuration
      ansible.builtin.include_vars: config.yml

  tasks:
    - name: install required packages
      ansible.builtin.import_tasks: tasks/install_packages.yml

    - name: change shell to fish
      ansible.builtin.import_tasks: tasks/config_fish.yml

    - name: install yadm
      ansible.builtin.import_tasks: tasks/yadm_install.yml

    - name: clone the repo
      ansible.builtin.import_tasks: tasks/yadm_clone.yml

    - name: install starship
      ansible.builtin.import_tasks: tasks/starship_install.yml
