---
- hosts: all

  pre_tasks:
    - name: load configuration
      ansible.builtin.include_vars: config.yml

  tasks:
    - name: install yadm
      ansible.builtin.import_tasks: tasks/yadm_install.yml

    - name: clone the repo
      ansible.builtin.import_tasks: tasks/yadm_clone.yml

    - name: install starship
      ansible.builtin.import_tasks: tasks/starship_install.yml
