---
- name: check if dotfile repo has already been cloned
  ansible.builtin.stat:
    path: "{{ dotfiles_repo_path }}"
  register: dotfiles_repo_exists

- name: clone dotfiles
  ansible.builtin.command: "{{ ansible_user_dir }}/.local/bin/yadm clone {{ dotfiles_repo }}"
  args:
    chdir: "~/"
  when: not dotfiles_repo_exists.stat.exists

- name: configure dotfiles class
  ansible.builtin.command: "{{ ansible_user_dir }}/.local/bin/yadm config local.class {{ dotfiles_class }}"

- name: materialize dotfiles alternates
  ansible.builtin.command: "{{ ansible_user_dir }}/.local/bin/yadm alt"

- name: check out dotfiles
  ansible.builtin.command: "{{ ansible_user_dir }}/.local/bin/yadm checkout ~/"
  when: not dotfiles_repo_exists.stat.exists
