---
- name: check if plugin tmux plugins is already installed
  stat:
    path: ~/.tmux/plugins/tpm
  register: tmux_exists

- name: create destination directory
  ansible.builtin.command: mkdir -p ~/.tmux/plugins/tpm
  when: not tmux_exists.stat.exists

- name: download tpm
  ansible.builtin.command: git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
  when: not tmux_exists.stat.exists