---
- name: check if plugin ohmyzsh is already installed
  stat:
    path: ~/.tmux/plugins/tpm
  register: tmux_exists

- name: create destination directory
  file:
    path: "~/.tmux/plugins/tpm"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: '0755'
  when: not tmux_exists.stat.exists

- name: download tpm
  ansible.builtin.command: git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
  when: not tmux_exists.stat.exists