---
- name: install requirements (linux)
  become: true
  ansible.builtin.package:
    name: 
      - fish
      - vim
      - git
    state: present
  when: ansible_facts.os_family == "Debian" or ansible_facts.os_family == "RedHat"

- name: install requirements (mac)
  community.general.homebrew:
    name: 
      - fish
      - vim
      - git
      - starship
      - yadm
    state: present
  when: ansible_facts.os_family == "Darwin"

# https://stackoverflow.com/a/41608975/17214978 -> for the AmazonLinux check
- name: add fish repo
  become: true
  ansible.builtin.shell: |
    cd /etc/yum.repos.d/
    wget https://download.opensuse.org/repositories/shells:fish:release:3/CentOS_8/shells:fish:release:3.repo
  args:
    executable: /bin/bash
  when: ansible_distribution == "Amazon"

- name: upgrade all packages
  become: true
  yum:
    name: '*'
    update_cache: true
  when: ansible_distribution == "Amazon"

- name: install fish and required packages
  become: true
  yum:
    name:
      - fish
      - git
  when: ansible_distribution == "Amazon"
